// Generated by rstantools.  Do not edit by hand.

/*
    PoolTestR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PoolTestR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with PoolTestR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_PoolPrev_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'string', line 10, column 2 to column 27)",
                                                      " (in 'string', line 13, column 2 to column 37)",
                                                      " (in 'string', line 14, column 2 to column 9)",
                                                      " (in 'string', line 15, column 2 to column 10)",
                                                      " (in 'string', line 17, column 4 to column 26)",
                                                      " (in 'string', line 18, column 4 to column 19)",
                                                      " (in 'string', line 16, column 15 to line 19, column 3)",
                                                      " (in 'string', line 16, column 2 to line 19, column 3)",
                                                      " (in 'string', line 31, column 4 to column 35)",
                                                      " (in 'string', line 30, column 7 to line 32, column 3)",
                                                      " (in 'string', line 23, column 4 to column 11)",
                                                      " (in 'string', line 24, column 4 to column 10)",
                                                      " (in 'string', line 26, column 8 to column 30)",
                                                      " (in 'string', line 27, column 8 to column 52)",
                                                      " (in 'string', line 25, column 17 to line 28, column 5)",
                                                      " (in 'string', line 25, column 4 to line 28, column 5)",
                                                      " (in 'string', line 29, column 4 to column 23)",
                                                      " (in 'string', line 22, column 19 to line 30, column 3)",
                                                      " (in 'string', line 22, column 2 to line 32, column 3)",
                                                      " (in 'string', line 33, column 2 to column 25)",
                                                      " (in 'string', line 2, column 2 to column 17)",
                                                      " (in 'string', line 3, column 8 to column 9)",
                                                      " (in 'string', line 3, column 2 to column 40)",
                                                      " (in 'string', line 4, column 18 to column 19)",
                                                      " (in 'string', line 4, column 2 to column 30)",
                                                      " (in 'string', line 5, column 2 to column 27)",
                                                      " (in 'string', line 6, column 2 to column 26)",
                                                      " (in 'string', line 7, column 2 to column 38)",
                                                      " (in 'string', line 13, column 8 to column 9)"};
#include <stan_meta_header.hpp>
class model_PoolPrev final : public model_base_crtp<model_PoolPrev> {
private:
  int N;
  std::vector<int> Result;
  Eigen::Matrix<double, -1, 1> PoolSize;
  double PriorAlpha;
  double PriorBeta;
  int JeffreysPrior;
 
public:
  ~model_PoolPrev() { }
  
  inline std::string model_name() const final { return "model_PoolPrev"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_PoolPrev(stan::io::var_context& context__,
                 unsigned int random_seed__ = 0,
                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_PoolPrev_namespace::model_PoolPrev";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 21;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 21;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 21;
      current_statement__ = 21;
      check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 22;
      validate_non_negative_index("Result", "N", N);
      current_statement__ = 23;
      context__.validate_dims("data initialization","Result","int",
          context__.to_vec(N));
      Result = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 23;
      assign(Result, nil_index_list(), context__.vals_i("Result"),
        "assigning variable Result");
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_greater_or_equal(function__, "Result[sym1__]",
                               Result[(sym1__ - 1)], 0);}
      current_statement__ = 23;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 23;
        current_statement__ = 23;
        check_less_or_equal(function__, "Result[sym1__]",
                            Result[(sym1__ - 1)], 1);}
      current_statement__ = 24;
      validate_non_negative_index("PoolSize", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization","PoolSize","double",
          context__.to_vec(N));
      PoolSize = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(PoolSize, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> PoolSize_flat__;
        current_statement__ = 25;
        assign(PoolSize_flat__, nil_index_list(),
          context__.vals_r("PoolSize"), "assigning variable PoolSize_flat__");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 25;
          assign(PoolSize, cons_list(index_uni(sym1__), nil_index_list()),
            PoolSize_flat__[(pos__ - 1)], "assigning variable PoolSize");
          current_statement__ = 25;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 25;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 25;
        current_statement__ = 25;
        check_greater_or_equal(function__, "PoolSize[sym1__]",
                               PoolSize[(sym1__ - 1)], 0);}
      current_statement__ = 26;
      context__.validate_dims("data initialization","PriorAlpha","double",
          context__.to_vec());
      PriorAlpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 26;
      PriorAlpha = context__.vals_r("PriorAlpha")[(1 - 1)];
      current_statement__ = 26;
      current_statement__ = 26;
      check_greater_or_equal(function__, "PriorAlpha", PriorAlpha, 0);
      current_statement__ = 27;
      context__.validate_dims("data initialization","PriorBeta","double",
          context__.to_vec());
      PriorBeta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 27;
      PriorBeta = context__.vals_r("PriorBeta")[(1 - 1)];
      current_statement__ = 27;
      current_statement__ = 27;
      check_greater_or_equal(function__, "PriorBeta", PriorBeta, 0);
      current_statement__ = 28;
      context__.validate_dims("data initialization","JeffreysPrior","int",
          context__.to_vec());
      JeffreysPrior = std::numeric_limits<int>::min();
      
      current_statement__ = 28;
      JeffreysPrior = context__.vals_i("JeffreysPrior")[(1 - 1)];
      current_statement__ = 28;
      current_statement__ = 28;
      check_greater_or_equal(function__, "JeffreysPrior", JeffreysPrior, 0);
      current_statement__ = 28;
      current_statement__ = 28;
      check_less_or_equal(function__, "JeffreysPrior", JeffreysPrior, 1);
      current_statement__ = 29;
      validate_non_negative_index("ps", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_PoolPrev_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ p;
      p = DUMMY_VAR__;
      
      current_statement__ = 1;
      p = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        p = stan::math::lub_constrain(p, 0, 1, lp__);
      } else {
        current_statement__ = 1;
        p = stan::math::lub_constrain(p, 0, 1);
      }
      std::vector<local_scalar_t__> ps;
      ps = std::vector<local_scalar_t__>(N, DUMMY_VAR__);
      
      local_scalar_t__ q;
      q = DUMMY_VAR__;
      
      current_statement__ = 4;
      q = (1 - p);
      current_statement__ = 8;
      for (int n = 1; n <= N; ++n) {
        local_scalar_t__ PS;
        PS = DUMMY_VAR__;
        
        current_statement__ = 5;
        PS = PoolSize[(n - 1)];
        current_statement__ = 6;
        assign(ps, cons_list(index_uni(n), nil_index_list()),
          (1 - pow(q, PS)), "assigning variable ps");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        current_statement__ = 2;
        check_greater_or_equal(function__, "ps[sym1__]", ps[(sym1__ - 1)], 0);
      }
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        current_statement__ = 2;
        check_less_or_equal(function__, "ps[sym1__]", ps[(sym1__ - 1)], 1);}
      {
        current_statement__ = 19;
        if (JeffreysPrior) {
          local_scalar_t__ s;
          s = DUMMY_VAR__;
          
          current_statement__ = 12;
          s = 0;
          current_statement__ = 16;
          for (int n = 1; n <= N; ++n) {
            local_scalar_t__ PS;
            PS = DUMMY_VAR__;
            
            current_statement__ = 13;
            PS = PoolSize[(n - 1)];
            current_statement__ = 14;
            s = (s + ((pow(PS, 2.0) * pow(q, (PS - 2))) / (1 - pow(q, PS))));
          }
          current_statement__ = 17;
          lp_accum__.add((stan::math::log(s) / 2));
        } else {
          current_statement__ = 9;
          lp_accum__.add(beta_lpdf<propto__>(p, PriorAlpha, PriorBeta));
        }
        current_statement__ = 20;
        lp_accum__.add(bernoulli_lpmf<propto__>(Result, ps));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_PoolPrev_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double p;
      p = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      p = in__.scalar();
      current_statement__ = 1;
      p = stan::math::lub_constrain(p, 0, 1);
      std::vector<double> ps;
      ps = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      double q;
      q = std::numeric_limits<double>::quiet_NaN();
      
      vars__.emplace_back(p);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 4;
      q = (1 - p);
      current_statement__ = 8;
      for (int n = 1; n <= N; ++n) {
        double PS;
        PS = std::numeric_limits<double>::quiet_NaN();
        
        current_statement__ = 5;
        PS = PoolSize[(n - 1)];
        current_statement__ = 6;
        assign(ps, cons_list(index_uni(n), nil_index_list()),
          (1 - pow(q, PS)), "assigning variable ps");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        current_statement__ = 2;
        check_greater_or_equal(function__, "ps[sym1__]", ps[(sym1__ - 1)], 0);
      }
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 2;
        current_statement__ = 2;
        check_less_or_equal(function__, "ps[sym1__]", ps[(sym1__ - 1)], 1);}
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(ps[(sym1__ - 1)]);}
        vars__.emplace_back(q);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double p;
      p = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      p = context__.vals_r("p")[(1 - 1)];
      double p_free__;
      p_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      p_free__ = stan::math::lub_free(p, 0, 1);
      vars__.emplace_back(p_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("p");
    names__.emplace_back("ps");
    names__.emplace_back("q");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "p");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ps" + '.' + std::to_string(sym1__));
        }}
      param_names__.emplace_back(std::string() + "q");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "p");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "ps" + '.' + std::to_string(sym1__));
        }}
      param_names__.emplace_back(std::string() + "q");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"p\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ps\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"q\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"p\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ps\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"q\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_PoolPrev_namespace::model_PoolPrev;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_PoolPrev_namespace::profiles__;
}
#endif
#endif
